project_id = "ruvdqtqyfzaxlobmxgaj"

[functions.send-password-reset]
verify_jwt = false

[functions.cash-flow-advice]
verify_jwt = false

[functions.generate-daily-insights]
verify_jwt = false

[functions.cash-flow-chat]
verify_jwt = false